import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import path from "node:path";
import { defineConfig } from "vite";
import { VitePWA } from "vite-plugin-pwa";

const shared = path.resolve(__dirname, "../supabase/functions/_shared");

export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    VitePWA({
      registerType: "autoUpdate",
      includeAssets: ["favicon-48.png", "apple-touch-icon.png"],
      workbox: {
        // Offline: the app itself is precached; data you've loaded is kept too.
        runtimeCaching: [
          {
            // Supabase data (read-only requests). Network first so it's fresh when
            // online; the last copy is used when offline or after 5 s of waiting.
            urlPattern: ({ url, request }) =>
              request.method === "GET" && url.hostname.endsWith(".supabase.co") && url.pathname.startsWith("/rest/v1/"),
            handler: "NetworkFirst",
            options: {
              cacheName: "rafiq-data",
              networkTimeoutSeconds: 5,
              expiration: { maxEntries: 1000, maxAgeSeconds: 60 * 60 * 24 * 60 },
              cacheableResponse: { statuses: [200] },
            },
          },
          {
            // The Arabic font, so text still renders properly offline.
            urlPattern: ({ url }) => url.hostname === "fonts.googleapis.com" || url.hostname === "fonts.gstatic.com",
            handler: "CacheFirst",
            options: {
              cacheName: "rafiq-fonts",
              expiration: { maxEntries: 30, maxAgeSeconds: 60 * 60 * 24 * 365 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
        ],
      },
      manifest: {
        id: "/",
        name: "Rafiq — Arabic Class Companion",
        short_name: "Rafiq",
        description: "Learn Arabic from the first letter: the alphabet with sounds, everyday conversation, and every page of your textbook explained with audio.",
        lang: "en",
        dir: "ltr",
        start_url: "/",
        scope: "/",
        display: "standalone",
        orientation: "portrait",
        background_color: "#f7f5f0",
        theme_color: "#2f5d50",
        categories: ["education"],
        // Generated by scripts/make-icons.mjs
        icons: [
          { src: "icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
          { src: "icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
          { src: "icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
        ],
      },
    }),
  ],
  // Pure TypeScript shared with the edge functions (vowel-mark diff, card types).
  resolve: { alias: { "@shared": shared } },
  server: { fs: { allow: [".", shared] } },
});
