// Writes the migration that seeds built-in Level 1 cards (letter names, short
// and long vowel sounds) from supabase/functions/_shared/sounds.ts.
//
//   node scripts/gen-builtin-cards.ts
import fs from "node:fs";
import { builtinSoundCards } from "../supabase/functions/_shared/sounds.ts";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const rows = builtinSoundCards()
  .map((c) => `    (${q(c.builtin_key)}, ${q(c.kind)}, ${q(c.arabic)}, ${q(c.tts_text)}, ${q(c.pronunciation)}, ${q(c.english)})`)
  .join(",\n");

const sql = `-- Built-in course, Level 1 (Sounds): every letter's name and its short and long
-- vowel sounds, in the book's letter order. Generated by scripts/gen-builtin-cards.ts.
-- Also: a review streak on progress for spaced repetition.

alter table public.cards add column builtin_key text unique;
alter table public.progress add column streak int not null default 0;

do $$
declare
  r record;
  v_card uuid;
begin
  for r in select * from (values
${rows}
  ) as t(builtin_key, kind, arabic, tts_text, pronunciation, english)
  loop
    insert into public.cards (level, kind, builtin_key) values (1, r.kind, r.builtin_key)
    on conflict (builtin_key) do nothing
    returning id into v_card;
    if v_card is not null then
      insert into public.card_versions (card_id, version, arabic_printed, arabic_full, tts_text, pronunciation, english, reason)
      values (v_card, 1, r.arabic, r.arabic, r.tts_text, r.pronunciation, r.english, 'built-in');
    end if;
  end loop;
end $$;
`;
fs.writeFileSync("supabase/migrations/20260930150000_builtin_sound_cards.sql", sql);
console.log(`${builtinSoundCards().length} built-in cards written`);
