// Writes the migration that seeds built-in Level 4 (everyday conversation) cards
// from supabase/functions/_shared/conversations.ts. Re-run with a new file name
// (and bump the timestamp) whenever phrases are added; existing keys are skipped.
//
//   node scripts/gen-conversation-cards.ts 20260930170000
import fs from "node:fs";
import { conversationPhrases } from "../supabase/functions/_shared/conversations.ts";

const stamp = process.argv[2] ?? "20260930170000";
const q = (s: string | undefined) => (s === undefined ? "null" : `'${s.replace(/'/g, "''")}'`);
const phrases = conversationPhrases();
const kind = (arabic: string) => (arabic.trim().split(/\s+/).length > 3 ? "sentence" : arabic.includes(" ") ? "phrase" : "word");
const rows = phrases
  .map((p) => `    (${q(p.builtin_key)}, ${q(kind(p.arabic))}, ${q(p.arabic)}, ${q(p.tts)}, ${q(p.pron)}, ${q(p.english)}, ${q(p.note)})`)
  .join(",\n");

const sql = `-- Built-in course, Level 4 (Everyday conversation): greetings, how are you,
-- names, where you're from, age. Generated by scripts/gen-conversation-cards.ts
-- from supabase/functions/_shared/conversations.ts. Drafted content: to be
-- checked by a teacher or native speaker.

do $$
declare
  r record;
  v_card uuid;
begin
  for r in select * from (values
${rows}
  ) as t(builtin_key, kind, arabic, tts_text, pronunciation, english, sound_note)
  loop
    insert into public.cards (level, kind, builtin_key) values (4, r.kind, r.builtin_key)
    on conflict (builtin_key) do nothing
    returning id into v_card;
    if v_card is not null then
      insert into public.card_versions (card_id, version, arabic_printed, arabic_full, tts_text, pronunciation, english, sound_note, reason)
      values (v_card, 1, r.arabic, r.arabic, r.tts_text, r.pronunciation, r.english, r.sound_note, 'built-in draft');
    end if;
  end loop;
end $$;
`;
fs.writeFileSync(`supabase/migrations/${stamp}_conversation_cards.sql`, sql);
console.log(`${phrases.length} conversation cards written`);
