-- Built-in course, Level 4 (Everyday conversation): greetings, how are you,
-- names, where you're from, age. Generated by scripts/gen-conversation-cards.ts
-- from supabase/functions/_shared/conversations.ts. Drafted content: to be
-- checked by a teacher or native speaker.

do $$
declare
  r record;
  v_card uuid;
begin
  for r in select * from (values
    ('conv-salam', 'phrase', 'السَّلَامُ عَلَيْكُمْ', 'اَلسَّلَامُ عَلَيْكُمْ', 'as-sa-LAA-mu ʿa-LAY-kum', 'Peace be upon you (hello)', 'The everyday greeting. Say it when you arrive, to one person or many.'),
    ('conv-salam-reply', 'phrase', 'وَعَلَيْكُمُ السَّلَامُ', 'وَعَلَيْكُمُ السَّلَامْ', 'wa-ʿa-LAY-ku-mus sa-LAAM', 'And peace be upon you (the reply)', null),
    ('conv-morning', 'phrase', 'صَبَاحُ الْخَيْرِ', 'صَبَاحُ الْخَيْرْ', 'ṣa-BAA-ḥul khayr', 'Good morning', null),
    ('conv-morning-reply', 'phrase', 'صَبَاحُ النُّورِ', 'صَبَاحُ النُّورْ', 'ṣa-BAA-ḥun nuur', 'Good morning (the reply: “morning of light”)', null),
    ('conv-evening', 'phrase', 'مَسَاءُ الْخَيْرِ', 'مَسَاءُ الْخَيْرْ', 'ma-SAA-ʾul khayr', 'Good afternoon / good evening', 'Used from the afternoon onwards.'),
    ('conv-evening-reply', 'phrase', 'مَسَاءُ النُّورِ', 'مَسَاءُ النُّورْ', 'ma-SAA-ʾun nuur', 'Good afternoon / good evening (the reply)', null),
    ('conv-welcome', 'phrase', 'أَهْلًا وَسَهْلًا', 'أَهْلًا وَسَهْلَا', 'AH-lan wa-SAH-laa', 'Welcome!', null),
    ('conv-goodbye', 'phrase', 'مَعَ السَّلَامَةِ', 'مَعَ السَّلَامَهْ', 'MA-ʿas sa-LAA-mah', 'Goodbye (“go with safety”)', null),
    ('conv-how-m', 'phrase', 'كَيْفَ حَالُكَ؟', 'كَيْفَ حَالُكَ؟', 'KAY-fa ḤAA-lu-ka', 'How are you? (to a man)', 'حَ is a breathy h from deep in the throat. End with -ka for a man.'),
    ('conv-how-f', 'phrase', 'كَيْفَ حَالُكِ؟', 'كَيْفَ حَالُكِ؟', 'KAY-fa ḤAA-lu-ki', 'How are you? (to a woman)', 'End with -ki for a woman.'),
    ('conv-fine', 'sentence', 'أَنَا بِخَيْرٍ، وَالْحَمْدُ لِلَّهِ', 'أَنَا بِخَيْرٍ، وَالْحَمْدُ لِلَّهْ', 'A-naa bi-KHAY-rin, wal-ḤAM-du lil-LAAH', 'I''m fine, thank God', 'خ is a rough kh at the back of the throat, like Scottish “loch”.'),
    ('conv-and-you-m', 'word', 'وَأَنْتَ؟', 'وَأَنْتَ؟', 'wa-AN-ta', 'And you? (to a man)', null),
    ('conv-and-you-f', 'word', 'وَأَنْتِ؟', 'وَأَنْتِ؟', 'wa-AN-ti', 'And you? (to a woman)', null),
    ('conv-thanks', 'word', 'شُكْرًا', 'شُكْرًا', 'SHUK-ran', 'Thank you', null),
    ('conv-welcome-reply', 'word', 'عَفْوًا', 'عَفْوًا', 'ʿAF-wan', 'You''re welcome', 'ع is a tight squeeze deep in the throat, not an English sound.'),
    ('conv-name-q-m', 'phrase', 'مَا اسْمُكَ؟', 'مَا اسْمُكَ؟', 'MAS-mu-ka', 'What''s your name? (to a man)', 'مَا and اسْمُكَ run together: “mas-mu-ka”.'),
    ('conv-name-q-f', 'phrase', 'مَا اسْمُكِ؟', 'مَا اسْمُكِ؟', 'MAS-mu-ki', 'What''s your name? (to a woman)', null),
    ('conv-my-name', 'phrase', 'اِسْمِي دَيْفِيد', 'اِسْمِي دَيْفِيدْ', 'IS-mii DAY-fiid', 'My name is David', 'Put your own name after اِسْمِي (ismii, “my name”).'),
    ('conv-nice-to-meet', 'word', 'تَشَرَّفْنَا', 'تَشَرَّفْنَا', 'ta-shar-RAF-naa', 'Nice to meet you (“we are honoured”)', null),
    ('conv-from-q-m', 'phrase', 'مِنْ أَيْنَ أَنْتَ؟', 'مِنْ أَيْنَ أَنْتَ؟', 'min AY-na AN-ta', 'Where are you from? (to a man)', null),
    ('conv-from-q-f', 'phrase', 'مِنْ أَيْنَ أَنْتِ؟', 'مِنْ أَيْنَ أَنْتِ؟', 'min AY-na AN-ti', 'Where are you from? (to a woman)', null),
    ('conv-from-nigeria', 'phrase', 'أَنَا مِنْ نَيْجِيرْيَا', 'أَنَا مِنْ نَيْجِيرْيَا', 'A-naa min nay-JIIR-yaa', 'I''m from Nigeria', null),
    ('conv-from-egypt', 'phrase', 'أَنَا مِنْ مِصْرَ', 'أَنَا مِنْ مِصْرْ', 'A-naa min miṣr', 'I''m from Egypt', 'ص is a heavy s: say it with the tongue low and the mouth round.'),
    ('conv-age-q-m', 'phrase', 'كَمْ عُمْرُكَ؟', 'كَمْ عُمْرُكَ؟', 'kam ʿUM-ru-ka', 'How old are you? (to a man)', null),
    ('conv-age-q-f', 'phrase', 'كَمْ عُمْرُكِ؟', 'كَمْ عُمْرُكِ؟', 'kam ʿUM-ru-ki', 'How old are you? (to a woman)', null),
    ('conv-age-20', 'phrase', 'عُمْرِي عِشْرُونَ سَنَةً', 'عُمْرِي عِشْرُونَ سَنَهْ', 'ʿUM-rii ʿish-RUU-na SA-nah', 'I am twenty years old', 'عُمْرِي (ʿumrii) means “my age”; then the number and سَنَة (year).'),
    ('conv-age-30', 'phrase', 'عُمْرِي ثَلَاثُونَ سَنَةً', 'عُمْرِي ثَلَاثُونَ سَنَهْ', 'ʿUM-rii tha-laa-THUU-na SA-nah', 'I am thirty years old', 'ث is th as in “think”.')
  ) as t(builtin_key, kind, arabic, tts_text, pronunciation, english, sound_note)
  loop
    insert into public.cards (level, kind, builtin_key) values (4, r.kind, r.builtin_key)
    on conflict (builtin_key) do nothing
    returning id into v_card;
    if v_card is not null then
      insert into public.card_versions (card_id, version, arabic_printed, arabic_full, tts_text, pronunciation, english, sound_note, reason)
      values (v_card, 1, r.arabic, r.arabic, r.tts_text, r.pronunciation, r.english, r.sound_note, 'built-in draft');
    end if;
  end loop;
end $$;
